# Generated by Django 6.1 on 2026-08-20 12:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nama Item')),
                ('condition', models.CharField(choices=[('layak_makan', 'Masih Layak Dimakan'), ('byproduct', 'Byproduct')], max_length=20)),
                ('listing_type', models.CharField(blank=True, choices=[('diskon', 'Jual Diskon'), ('donasi', 'Donasi')], max_length=20, null=True)),
                ('quantity_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity_remaining', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(choices=[('kg', 'Kilogram'), ('liter', 'Liter'), ('pcs', 'Pcs'), ('bungkus', 'Bungkus'), ('porsi', 'Porsi')], max_length=20)),
                ('description', models.TextField(blank=True, verbose_name='Deskripsi')),
                ('category', models.CharField(blank=True, max_length=100, verbose_name='Kategori')),
                ('pickup_start', models.TimeField(blank=True, null=True)),
                ('pickup_end', models.TimeField(blank=True, null=True)),
                ('pickup_date_start', models.DateField(blank=True, null=True)),
                ('pickup_date_end', models.DateField(blank=True, null=True)),
                ('price_original', models.PositiveIntegerField(blank=True, null=True, verbose_name='Harga Asli')),
                ('price_sale', models.PositiveIntegerField(blank=True, null=True, verbose_name='Harga Jual')),
                ('best_before', models.DateField(blank=True, null=True, verbose_name='Baik Dikonsumsi Sebelum')),
                ('status', models.CharField(choices=[('tersedia', 'Tersedia'), ('tersedia_sebagian', 'Tersedia (sebagian)'), ('habis', 'Habis'), ('kadaluarsa', 'Kadaluarsa')], default='tersedia', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_lengkap', models.CharField(max_length=255)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ItemImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='items/%Y/%m/')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='items.item')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Klaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah_diklaim', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='klaim_list', to='items.item')),
                ('peminat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_toko', models.CharField(max_length=150)),
                ('kontak_wa', models.CharField(max_length=20)),
                ('lokasi', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='items.location')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='store', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='items.store'),
        ),
    ]
