# Generated by Django 6.1 on 2026-08-18 09:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nama Item')),
                ('condition', models.CharField(choices=[('layak_makan', 'Masih Layak Dimakan'), ('byproduct', 'Byproduct')], max_length=20)),
                ('quantity_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity_remaining', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(choices=[('kg', 'Kilogram'), ('liter', 'Liter'), ('pcs', 'Pcs'), ('bungkus', 'Bungkus'), ('porsi', 'Porsi')], max_length=20)),
                ('location_text', models.CharField(max_length=255, verbose_name='Lokasi')),
                ('location_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('location_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('whatsapp_number', models.CharField(max_length=20, verbose_name='Kontak WA')),
                ('description', models.TextField(blank=True, verbose_name='Deskripsi')),
                ('category', models.CharField(blank=True, max_length=100, verbose_name='Kategori')),
                ('pickup_start', models.TimeField(verbose_name='Jam Ambil Mulai')),
                ('pickup_end', models.TimeField(verbose_name='Jam Ambil Selesai')),
                ('price_original', models.PositiveIntegerField(blank=True, null=True, verbose_name='Harga Asli')),
                ('price_sale', models.PositiveIntegerField(blank=True, null=True, verbose_name='Harga Jual')),
                ('best_before', models.DateField(blank=True, null=True, verbose_name='Baik Dikonsumsi Sebelum')),
                ('status', models.CharField(choices=[('tersedia', 'Tersedia'), ('tersedia_sebagian', 'Tersedia (sebagian)'), ('habis', 'Habis'), ('selesai', 'Selesai'), ('kadaluarsa', 'Kadaluarsa')], default='tersedia', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ItemImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='items/%Y/%m/')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='items.item')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
