# Generated by Django 6.1 on 2026-08-18 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='location_lat',
        ),
        migrations.RemoveField(
            model_name='item',
            name='location_lng',
        ),
        migrations.RemoveField(
            model_name='item',
            name='location_text',
        ),
        migrations.RemoveField(
            model_name='item',
            name='whatsapp_number',
        ),
    ]
