# Generated by Django 6.1 on 2026-08-20 18:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_remove_item_location_lat_remove_item_location_lng_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_lengkap', models.CharField(max_length=255)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='item',
            name='seller',
        ),
        migrations.AddField(
            model_name='item',
            name='listing_type',
            field=models.CharField(blank=True, choices=[('diskon', 'Jual Diskon'), ('donasi', 'Donasi')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='pickup_date_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='pickup_date_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='pickup_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='pickup_start',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.CharField(choices=[('tersedia', 'Tersedia'), ('tersedia_sebagian', 'Tersedia (sebagian)'), ('habis', 'Habis'), ('kadaluarsa', 'Kadaluarsa')], default='tersedia', max_length=20),
        ),
        migrations.CreateModel(
            name='Klaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah_diklaim', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='klaim_list', to='items.item')),
                ('peminat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_toko', models.CharField(max_length=150)),
                ('kontak_wa', models.CharField(max_length=20)),
                ('lokasi', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='items.location')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='store', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='store',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='items.store'),
            preserve_default=False,
        ),
    ]
