# Generated by Django 6.1 on 2026-08-21 03:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_location_remove_item_seller_item_listing_type_and_more'),
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='lokasi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.location'),
        ),
        migrations.AddField(
            model_name='item',
            name='is_reported',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='klaim',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='klaim',
            name='status',
            field=models.CharField(choices=[('Menunggu', 'Menunggu'), ('Selesai', 'Selesai'), ('Batal', 'Batal')], default='Menunggu', max_length=20),
        ),
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.CharField(choices=[('Tersedia', 'Tersedia'), ('Tersedia Sebagian', 'Tersedia Sebagian'), ('Habis', 'Habis'), ('Selesai', 'Selesai'), ('Kadaluarsa', 'Kadaluarsa')], default='Tersedia', max_length=20),
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
