# Generated by Django 6.1 on 2026-08-26 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_alter_store_lokasi_item_is_reported_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='klaim',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='klaim',
            name='address_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='klaim',
            name='address_lng',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='klaim',
            name='address_text',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='klaim',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='klaim',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='klaim',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='klaim',
            name='pickup_method',
            field=models.CharField(choices=[('Self Pickup', 'Self Pickup'), ('Ojek', 'Ojek')], default='Self Pickup', max_length=20),
        ),
        migrations.AddField(
            model_name='klaim',
            name='pickup_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='klaim',
            name='price_at_claim',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='klaim',
            name='shipping_cost',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='klaim',
            name='total_price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='store',
            name='qris_image',
            field=models.ImageField(blank=True, null=True, upload_to='qris/'),
        ),
        migrations.AlterField(
            model_name='klaim',
            name='status',
            field=models.CharField(choices=[('Menunggu Pembayaran', 'Menunggu Pembayaran'), ('Dibayar', 'Dibayar'), ('Selesai', 'Selesai'), ('Batal', 'Batal')], default='Menunggu Pembayaran', max_length=30),
        ),
    ]
