# Generated by Django 6.1 on 2026-08-26 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_alter_klaim_options_klaim_address_lat_and_more'),
        ('items', '0005_store_description_store_logo'),
    ]

    operations = [
    ]
