# Generated by Django 6.1 on 2026-08-28 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0007_cartitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.CharField(choices=[('Tersedia', 'Tersedia'), ('Habis', 'Habis'), ('Selesai', 'Selesai'), ('Kadaluarsa', 'Kadaluarsa')], default='Tersedia', max_length=20),
        ),
    ]
