# Generated by Django 6.1 on 2026-08-20 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='forumreply',
            options={'ordering': ['created_at', 'id']},
        ),
        migrations.AlterModelOptions(
            name='forumthread',
            options={'ordering': ['-created_at', '-id']},
        ),
    ]
